[features]
seeds = false
skip-lint = false

[programs.localnet]
scooby = "3V9kdabTMdzTLudPjEP8gj5AFfRR2c8b4UyeWZMA2thT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
